### ISSUE TITLE
Does not find gulp tasks in gulpfile.babel.js

### ISSUE THREAD

**Issue by tmoitie** [AtomBuild/atom-build-gulp#1]

**Comment by maxwowpow** [comment]
doesn't load tasks from any custom file, a typical dev env with build process has many gulpfiles which are named differently. Brackets' extension recognizes every single of them without any configuration.

**Comment by noseglid** [comment]
it "should" work. There is even a [test for it](https://github.com/AtomBuild/atom-build-gulp/blob/master/spec/build-gulp-spec.js#L140-L160).

Do you have `gulp` installed in the project root (e.g does `<your project>/node_modules/.bin/gulp` exist?)

**Comment by maxwowpow** [comment]
hi, yes, gulp.cmd is there. My tasks are in `<my_project>/tasks/x.js` `y.js` and so on.
I get error "No configuration to build this project exists."
Thanks for response.

**Comment by noseglid** [comment]
What does your `gulpfile.babel.js` look like, and where is it located?

**Comment by maxwowpow** [comment]
Is it for testing there or it's an "required" config file for this plugin? I don't have one, it's not documented anywhere and from the users' side they normally should not debug extensions (I'm not fluent in coffee-script).
Upd: I have this in `<my_proj>\gulpfile.js`:

```
var requireDir = require('require-dir'),
    dir = requireDir('./tasks');
```

**Comment by noseglid** [comment]
That setup works fine for me. I have this:

`gulpfile.js`:

```
var requireDir = require('require-dir'),
    dir = requireDir('./tasks');
```

`tasks/a.js`:

```
var gulp = require('gulp');

gulp.task('from tasks folder', function () {
  console.log('cool beans');
});
```

`tasks/b.js`:

```
var gulp = require('gulp');

gulp.task('the b task', function () {
  console.log('cool b-b-b-eans');
});
```

![screen shot 2015-12-15 at 13 28 32](https://cloud.githubusercontent.com/assets/933880/11810648/dcdd8c04-a32f-11e5-9bb8-e45fabdff3bb.png)

**Comment by simonknittel** [comment]
For me it finds only the 'default' task. Here is the part of my gulpfile.babel.js

``` javascript
gulp.task('default', gulp.parallel('images', 'scripts:dev', 'styles:dev', 'html:dev', 'copy'));
gulp.task('production', gulp.parallel('images', 'scripts:prod', 'styles:prod', 'html:prod', 'copy'));
```

When I want to select the active build target there is only 'default' available.

**Comment by noseglid** [comment]
Do you have `gulp`, `babel` and `babel-core` installed in the project?

**Comment by simonknittel** [comment]
Yes and the gulpfile works correctly when I start it through the Gulp CLI or other tools. The 'default' task works with this package too. The only problem is, that I can not select the other tasks with this package.

**Comment by akfish** [comment]
I've got the same issue the other day. I solved it by adding `'use babel'` at the first line of my `gulpfile.babel.js`. `'use strict'` will not do for atom-build (but it works in CLI).

If this does not work for you, try find your local atom-build-gulp installation and add `throw e;` <del>before</del> after [this line](https://github.com/AtomBuild/atom-build-gulp/blob/master/lib/parser-task.js#L22) and see what the console output is. That's how I found my solution in the first place.

@noseglid Maybe atom-build-gulp could output detailed reasons for the parsing error in additional to falling back to default task in the future?

**Comment by noseglid** [comment]
Yes, better error output is always a good thing.
@akfish A minor correction to your instructions. it should be **after** [that](https://github.com/AtomBuild/atom-build-gulp/blob/master/lib/parser-task.js#L22) line, right?

**Comment by simonknittel** [comment]
That `'use babel';` does not work for me.

The error throws me this one:

```
Unexpected reserved word SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.defineProperty.value [as .js] (C:\Users\sknit\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.exports.default (C:/Users/sknit/.atom/packages/build-gulp/lib/parser-task.js:19:5)
    at process.<anonymous> (C:\Users\sknit\AppData\Local\atom\app-1.3.2\resources\app.asar\src\task-bootstrap.js:84:10)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by noseglid** [comment]
What's the name of your gulpfile?

**Comment by simonknittel** [comment]
gulpfile.babel.js

**Comment by noseglid** [comment]
Could you give the contents, verbatim please.

**Comment by simonknittel** [comment]
[gulpfile.babel.js](https://github.com/simonknittel/static-site-template/blob/master/gulpfile.babel.js)
[Modules](https://github.com/simonknittel/static-site-template/tree/master/_gulpfile)

[Full project](https://github.com/simonknittel/static-site-template)

**Comment by noseglid** [comment]
hmm, so if you take the gulpfile down to some really basic, does it work? e.g.

`gulpfile.babel.js`

```
'use babel';

import 'gulp' from gulp;

gulp.task('task', () => { console.log('my task'); })
```

**Comment by akfish** [comment]
@noseglid Yep. I meant after.

@simonknittel That's exactly the same error I ran into. FYI, here is my environment:

```
PS F:\dev\js\fractal.js> gulp -v
[07:00:05] Requiring external module babel-core/register
[07:00:05] CLI version 3.9.0
[07:00:05] Local version 3.9.0
PS F:\dev\js\fractal.js> atom -v

1.3.2
PS F:\dev\js\fractal.js> cat package.json
{
  "name": "fractal.js",
  "version": "1.0.0",
  "description": "Interactive fractal rendering",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.3.21",
    "babel-preset-es2015": "^6.3.13",
    "babelify": "^7.2.0",
    "browser-sync": "^2.10.1",
    "browserify": "^12.0.1",
    "gulp": "^3.9.0",
    "gulp-babel": "^6.1.1",
    "gulp-heap": "^2.0.0-alpha.1",
    "gulp-mocha": "^2.2.0",
    "gulp-uglify": "^1.5.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
  }
}
```

I noticed that your babel versions are older than mine. Perhaps that's why `'use babel;'` did not work for you?

**Comment by simonknittel** [comment]
Looks like build-gulp is not compatible with Gulp 4 (yeah, it's in the alpha/beta).

Updating my babel did not work. But downgrading from Gulp 4 to 3.9 did it.

Note: My gulpfile works with Gulp 4. The only thing that does not work is to get all tasks in build-gulp. It returns me only the `default` task. And running this one works too.

**Comment by noseglid** [comment]
I'm glad we found the reason. Since gulp4 is still in beta I will close this. If it doesn't work once released, please open a new issue and we will fix it there.

**Comment by justo** [comment]
I'm also having this exact issue but I am running gulp 3.9 (and not using babel). build-gulp doesn't find any of my tasks, only `default`.

By throwing the error in parser-tasks like @akfish recommended I can see the following in atom's console:

```
The `libsass` binding was not found in /myprojectdir/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version. Error: The `libsass` binding was not found in /myprojectdir/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```

The `darwin-x64-46/` dir its looking for doesn't exist, but `darwin-x64-47/` does. `npm rebuild node-sass` produces v47 again. If I change node versions to match atom's (`v4.1.1`, I was on `v5.3.0` before) and then rebuild I get the v46 that it is looking for. That error goes away but then when I try to refresh build targets it throws again with an `ENOENT: no such file or directory, open 'assets/manifest.json'` which is a file I'm requiring in gulpfile.js but didn't cause a problem before.

Any idea why this package is causing me problems?

**Comment by noseglid** [comment]
I don't know what's causing this. It seems as a version mis-match somewhere. It doesn't seem to be the same issue as describe by OP in this issue.
