### ISSUE TITLE
Refreshing targets fails if files with relative location are required by gulp-typescript

### ISSUE THREAD

**Issue by olee** [AtomBuild/atom-build-gulp#10]
Example:

``` js
var gulp = require('gulp');
var ts = require('gulp-typescript');
var tsProject = ts.createProject('./tsconfig.json');

gulp.task('task1', function() {
    console.log('my task');
});

gulp.task('task2', function() {
    console.log('my task');
});
```

Error from task resolver:
`"ENOENT: no such file or directory, open 'C:\Users\...\AppData\Local\atom\app-1.5.4\tsconfig.json'"`

**Comment by olee** [comment]
Ok I solved it by using `__dirname + '/tsconfig.json'` instead.
But I also noticed that

```
var sass = require('gulp-sass');
var npmRun = require('gulp-npm-run');
```

Cause the refresh to fail, because they seem to depend on the working directory.
Solved it by using this code instead:

```
var isTaskRefresh = process.cwd() != __dirname;
var sass = isTaskRefresh ? null : require('gulp-sass');
var npmRun = isTaskRefresh ? null : require('gulp-npm-run');
```

I can work with this, but you still might want to try **fixing the cwd for refreshing targets** if possible!

**Comment by noseglid** [comment]
I'm not sure how the `createProject` from `gulp-typescript` work, but the parser task that is spawned from this project will use [the project root as its cwd](https://github.com/AtomBuild/atom-build-gulp/blob/master/lib/gulp.js#L56).

**Comment by olee** [comment]
Well then why does it try to load
`C:\Users\...\AppData\Local\atom\app-1.5.4\package.json`? :smile: 
I wouldn't know any other way for it to get that path except from cwd.

**Comment by noseglid** [comment]
That's my question. Where does `gulp-typescript` resolve paths from? If it is indeed the current working directory, then Atom Task is not working properly.
