### ISSUE TITLE
Run custom task on build

### ISSUE THREAD

**Issue by EvAlex** [AtomBuild/atom-build-gulp#7]
This package absolutely need ability to run custom gulp task, not necessarily 'default'.

**Comment by noseglid** [comment]
It should extract all tasks available in the gulpfile and list those as targets, like so: 
![screen shot 2016-01-18 at 11 10 34](https://cloud.githubusercontent.com/assets/933880/12388619/2c1c2528-bdd4-11e5-88df-c17b5950514e.png)

Does this not work for you?

**Comment by noseglid** [comment]
Closing due to no response. Please re-open if the issue persists.
