### ISSUE TITLE
Version mismatch between native node and Atom-provided node prevents finding build targets

### ISSUE THREAD

**Issue by codl** [AtomBuild/atom-build-gulp#8]
I'm only getting the default build target from my gulpfile. Here's the error I get after inserting a `throw e;` at the appropriate place as suggested in another issue:

```
The `libsass` binding was not found in /(snip)/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```

My gulpfile requires `gulp-sass`, which requires `node-sass`. The binding is there, but in `vendor/linux-x64-47/`. Turns out Atom's version of node is way behind my installed version, and node C/C++ bindings are built specifically for one version, so Atom's built in node really should not be running gulpfiles directly.

**Comment by noseglid** [comment]
What is your `$PATH` environment? Could it be that the PATH to Atom's `node` is before your version?

**Comment by codl** [comment]
```
$ echo $PATH
/home/codl/.rvm/gems/ruby-2.1.5/bin:/home/codl/.rvm/gems/ruby-2.1.5@global/bin:/home/codl/.rvm/rubies/ruby-2.1.5/bin:/home/codl/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/codl/.rvm/bin
$ which node
/usr/bin/node
$ pacman -Ql atom-editor | grep -e 'bin/node$'
atom-editor /usr/share/atom/resources/app/apm/bin/node
```

Atom's `node` isn't in my PATH at all.

To clarify: building works fine, atom-build runs gulp without a hitch, but I can only select the default task.

I believe the problem lies here, where gulp is being required directly from Atom's `node` and the gulpfile gets parsed: https://github.com/AtomBuild/atom-build-gulp/blob/1d71e7304b8829e30cefdd192deacb70ba8de210/lib/parser-task.js#L11

**Comment by noseglid** [comment]
The line you're referring to is the gulp installed in your project. The parser task doesn't run with a globally installed gulp. You must do `npm install gulp` in your project root.

**Comment by codl** [comment]
Yeah, I am aware. I have installed gulp in my project already. But the task also is running on the node binary embedded in Atom, which is a different version from the one that runs when I `npm install` anything, locally or globally, which is what is causing the version mismatch.

![959d572b-b9c2-4a8e-b33e-4a67013c4eb6](https://cloud.githubusercontent.com/assets/315139/12974092/8621b4ee-d0b1-11e5-8f1d-7347c8638982.png)

**Comment by codl** [comment]
To add to the previous screenshot,
![d89e2a07-d2a4-4786-a804-24edc6330ec2](https://cloud.githubusercontent.com/assets/315139/12974353/942bcb0e-d0b3-11e5-94ab-d50072065cad.png)

**Comment by noseglid** [comment]
hmm, the `NODE_PATH` which is set to the parser task is here: `https://github.com/AtomBuild/atom-build-gulp/blob/master/lib/gulp.js#L54`.
I wonder what `PATH` is when that task is executed. It does indeed seem as it picks up the bundled node inside atom rather than your installation. Since you have it in `/usr/bin` I would suspect that should be picked up!

Could you just log `process.env` inside the parser task and paste the result here?

**Comment by codl** [comment]
Isn't `NODE_PATH` about finding modules only? It doesn't seem to be having trouble finding modules, the error is coming from node-sass because it doesn't have a binding for this version of node.

Either way it seems Task just forks from Atom's main node process, after all Atom is supposed to work even without node installed: https://github.com/atom/atom/blob/v1.4.3/src/task.coffee#L82

Anyway I stuck a `console.log(process.env.PATH)` just before the Task is created and inside the Task itself, both gave me 

```
/home/codl/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/bin
```

so, the same thing as above (without RVM because of irrelevant silly reasons)

**Comment by noseglid** [comment]
Ah good find! Maybe we should spawn our own instance to avoid this error. That way the specified PATH would be honored.
